name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*.*.*'

jobs:

  macos_windows_build:
    name: Build ${{ matrix.config.name }} ${{ matrix.python.name }} wheel
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {
            name: windows,
            os: windows-2019,
          }
        python:
          - {
            name: cp38,
            version: '3.8',
          }

    steps:
      - name: Setup GraalVM
        uses: ayltai/setup-graalvm@v1
        with:
          java-version: 11
          graalvm-version: 21.3.0
          native-image: true

#      - name: Checkout olf sources
#        uses: actions/checkout@v1
#        with:
#          repository: powsybl/powsybl-open-loadflow
#          ref: main
#
#      - name: Build and install olf artifact
#        run: mvn --batch-mode -DskipTests=true --file ../powsybl-open-loadflow/pom.xml install

      - name: Checkout sources
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python.version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Build wheel
        run: python setup.py bdist_wheel -- -- -j1

      - name: Build source archive
        if: matrix.config.name == 'darwin' && matrix.python.name == 'cp39'
        run: python setup.py sdist

      - name: Install wheel
        shell: bash
        run: python -m pip install dist/*.whl --user

      - name: Run tests
        working-directory: ./tests
        run: python3 -m unittest

      - name: Run doc examples
        working-directory: ./docs
        run: make doctest

      - name: Upload wheel
        uses: actions/upload-artifact@v2
        with:
          name: pypowsybl-wheel-${{ matrix.config.name }}-${{ matrix.python.name }}
          path: dist/*.whl

      - name: Upload source archive
        uses: actions/upload-artifact@v2
        if: matrix.config.name == 'darwin' && matrix.python.name == 'cp39'
        with:
          name: pypowsybl-sources
          path: dist/*.tar.gz
